name: Update Video Subtitle Remover Formula

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: false

jobs:
  update-formula:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release version
        id: get-version
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/eritpchy/video-subtitle-remover/tags | jq -r '.[0].name')
          echo "Latest tag: $LATEST_TAG"
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
          # 去掉版本号前面的v（如果有）
          VERSION=${LATEST_TAG#v}
          echo "Clean version: $VERSION"
          echo "clean_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download source tarball
        run: |
          VERSION=${{ steps.get-version.outputs.clean_version }}
          URL="https://github.com/eritpchy/video-subtitle-remover/archive/refs/tags/${{ steps.get-version.outputs.version }}.tar.gz"
          echo "Downloading from: $URL"
          curl -L -o /tmp/video-subtitle-remover.tar.gz "$URL"

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 /tmp/video-subtitle-remover.tar.gz | awk '{print $1}')
          echo "SHA256: $SHA256"
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          VERSION=${{ steps.get-version.outputs.clean_version }}
          SHA256=${{ steps.sha256.outputs.sha256 }}
          URL="https://github.com/eritpchy/video-subtitle-remover/archive/refs/tags/${{ steps.get-version.outputs.version }}.tar.gz"
          
          # 创建Formula目录（如果不存在）
          mkdir -p Formula
          
          # 读取模板并进行替换
          cat Template/video-subtitle-remover.rb | \
            sed "s|url \".*\"|url \"$URL\"|g" | \
            sed "s|sha256 \".*\"|sha256 \"$SHA256\"|g" | \
            sed "s|version \"1.0.0\"|version \"$VERSION\"|g" | \
            sed "s|<string>1.0.0</string>|<string>$VERSION</string>|g" > Formula/video-subtitle-remover.rb
          
          # 显示差异以便检查
          diff Template/video-subtitle-remover.rb Formula/video-subtitle-remover.rb || true

      - name: Upload formula as artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-subtitle-remover-formula
          path: Formula/video-subtitle-remover.rb
          retention-days: 1

  test-formula-x86:
    needs: update-formula
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download formula artifact
        uses: actions/download-artifact@v4
        with:
          name: video-subtitle-remover-formula
          path: Formula/
      
      - name: Start SSH via tmate
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        uses: mxschmitt/action-tmate@v3

      - name: Install formula
        run: |
          brew install -v Formula/video-subtitle-remover.rb

      - name: Test
        run: |
          ROOT_DIR="$(brew --prefix video-subtitle-remover)"
          sed -i.bak 's/HARDWARD_ACCELERATION_OPTION *= *.*/HARDWARD_ACCELERATION_OPTION = False/g' "$ROOT_DIR/backend/config.py"
          video-subtitle-remover-cli "--input" "$ROOT_DIR/test/test2.mp4" "-o" "/tmp/test2.mp4"

  test-formula-arm:
    needs: update-formula
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download formula artifact
        uses: actions/download-artifact@v4
        with:
          name: video-subtitle-remover-formula
          path: Formula/
      
      - name: Start SSH via tmate
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        uses: mxschmitt/action-tmate@v3

      - name: Install formula
        run: |
          brew install -v Formula/video-subtitle-remover.rb

      - name: Test
        run: |
          ROOT_DIR="$(brew --prefix video-subtitle-remover)"
          sed -i.bak 's/HARDWARD_ACCELERATION_OPTION *= *.*/HARDWARD_ACCELERATION_OPTION = False/g' "$ROOT_DIR/backend/config.py"
          video-subtitle-remover-cli "--input" "$ROOT_DIR/test/test2.mp4" "-o" "/tmp/test2.mp4"

  commit-formula:
    needs: [update-formula, test-formula-x86, test-formula-arm]
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download formula artifact
        uses: actions/download-artifact@v4
        with:
          name: video-subtitle-remover-formula
          path: Formula/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/video-subtitle-remover.rb
          git commit -m "Update video-subtitle-remover to ${{ needs.update-formula.outputs.version }}"
          git push
